"use strict";
exports.__esModule = true;
var express_1 = require("express");
var createProduct_1 = require("../controllers/products/createProduct");
var deleteProduct_1 = require("../controllers/products/deleteProduct");
var editProduct_1 = require("../controllers/products/editProduct");
var getProducts_1 = require("../controllers/products/getProducts");
var routes_1 = require("../utils/routes");
var products_1 = require("../validators/products");
var productRouter = (0, express_1.Router)();
productRouter.post('/create', products_1.validateCreateProduct, (0, routes_1.makeSafe)(createProduct_1.createProduct));
productRouter.post('/delete/init', products_1.validateInitDeleteProduct, (0, routes_1.makeSafe)(deleteProduct_1.initDeleteProduct));
productRouter.post('/delete/confirm', products_1.validateConfirmDeleteProduct, (0, routes_1.makeSafe)(deleteProduct_1.confirmDeleteProduct));
productRouter.post('/delete/cancel', products_1.validateCancelDeleteProduct, (0, routes_1.makeSafe)(deleteProduct_1.confirmDeleteProduct));
productRouter.post('/all', (0, routes_1.makeSafe)(getProducts_1.getAllProducts));
productRouter.post('/single', products_1.validateGetSingleProduct, (0, routes_1.makeSafe)(getProducts_1.getSingleProduct));
productRouter.post('/search', products_1.validateSearchProducts, (0, routes_1.makeSafe)(getProducts_1.searchProducts));
productRouter.post('/edit', products_1.validateEditProduct, (0, routes_1.makeSafe)(editProduct_1.editProduct));
exports["default"] = productRouter;
